# Generated by Django 3.2.7 on 2021-09-28 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='cpf',
            field=models.IntegerField(max_length=11),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='rg',
            field=models.IntegerField(max_length=8),
        ),
    ]
